### ISSUE TITLE
yo kai watch 1 switch xf image load error (IMGN)

### ISSUE THREAD

**Issue by RealDarkCraft** [onepiecefreak3/XFontEditor#2]
in ykw1 switch some XF have IMGN image so can't load
for this game the format hex value for IMGN in xf is 0x0E and that's L8 compression
and the swizzle need to be changed if the magic is not IMGC

**Comment by onepiecefreak3** [comment]
As described in the READ.ME, this is specifically for the 3DS. Switching to the switch formats is not intended.
